"""changed subscription model

Revision ID: 68398bbdfcdd
Revises: a872b4009988
Create Date: 2025-12-18 18:00:56.492654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68398bbdfcdd'
down_revision: Union[str, Sequence[str], None] = 'a872b4009988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('trainer_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'subscription', 'users', ['trainer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'trainer_id')
    # ### end Alembic commands ###
