"""changed models

Revision ID: 7a5c240fc5ea
Revises: 94e50ff58dd8
Create Date: 2025-12-10 14:50:13.631446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5c240fc5ea'
down_revision: Union[str, Sequence[str], None] = '94e50ff58dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_subscriptions', sa.Column('payment_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'daily_subscriptions', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_subscriptions', type_='foreignkey')
    op.drop_column('daily_subscriptions', 'payment_id')
    # ### end Alembic commands ###
