"""added new models

Revision ID: 81715b4add9f
Revises: abf16de409d7
Create Date: 2025-12-10 14:02:23.767973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81715b4add9f'
down_revision: Union[str, Sequence[str], None] = 'abf16de409d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('subscription', 'plan_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('subscription_user_id_fkey'), 'subscription', type_='foreignkey')
    op.create_foreign_key(None, 'subscription', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.create_foreign_key(op.f('subscription_user_id_fkey'), 'subscription', 'users', ['user_id'], ['id'])
    op.alter_column('subscription', 'plan_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('payments')
    op.drop_table('daily_attendance')
    # ### end Alembic commands ###
