"""changed models

Revision ID: a872b4009988
Revises: 7a5c240fc5ea
Create Date: 2025-12-10 15:03:01.894613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a872b4009988'
down_revision: Union[str, Sequence[str], None] = '7a5c240fc5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('daily_subscriptions_payment_id_fkey'), 'daily_subscriptions', type_='foreignkey')
    op.drop_column('daily_subscriptions', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_subscriptions', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('daily_subscriptions_payment_id_fkey'), 'daily_subscriptions', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###
