"""changed models

Revision ID: abf16de409d7
Revises: 4ef4075901ee
Create Date: 2025-12-04 16:40:50.814091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf16de409d7'
down_revision: Union[str, Sequence[str], None] = '4ef4075901ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('payment_method', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'payment_method')
    # ### end Alembic commands ###
