"""added new model

Revision ID: b80b1e675d73
Revises: 1f75d5d56d7c
Create Date: 2025-12-04 14:27:16.145570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80b1e675d73'
down_revision: Union[str, Sequence[str], None] = '1f75d5d56d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('subscription', 'status')
    op.alter_column('users', 'created_at',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('subscription', sa.Column('status', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_table('attendance')
    # ### end Alembic commands ###
